@php
    $comparison = $comparison ?? null;
@endphp

<div class="row g-3">

    {{-- Comparison Number --}}
    @if($comparison)
        <div class="col-md-6">

            <label class="form-label">
                Comparison Number
            </label>

            <input
                type="text"
                class="form-control"
                value="{{ $comparison->comparison_number }}"
                readonly
            >

            <div class="form-text">
                Automatically generated by the system.
            </div>

        </div>
    @endif


    {{-- Comparison Date --}}
    <div class="col-md-6">

        <label class="form-label">
            Comparison Date
        </label>

        <input
            type="date"
            name="comparison_date"
            class="form-control @error('comparison_date') is-invalid @enderror"
            value="{{ old(
                'comparison_date',
                $comparison?->comparison_date?->format('Y-m-d')
            ) }}"
        >

        @error('comparison_date')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror

    </div>


    {{-- Comparison Title --}}
    <div class="col-md-8">

        <label class="form-label">
            Comparison Title
            <span class="text-danger">*</span>
        </label>

        <input
            type="text"
            name="comparison_title"
            class="form-control @error('comparison_title') is-invalid @enderror"
            value="{{ old(
                'comparison_title',
                $comparison?->comparison_title
            ) }}"
            maxlength="255"
            placeholder="e.g. Financial Bid Comparison"
            required
        >

        @error('comparison_title')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror

    </div>


    {{-- Evaluation Basis --}}
    <div class="col-md-4">

        <label class="form-label">
            Evaluation Basis
            <span class="text-danger">*</span>
        </label>

        <select
            name="evaluation_basis"
            class="form-select @error('evaluation_basis') is-invalid @enderror"
            required
        >

            @foreach([
                'Lowest Evaluated Bid',
                'Best Value',
                'Combined Technical & Financial Score',
            ] as $basis)

                <option
                    value="{{ $basis }}"
                    @selected(
                        old(
                            'evaluation_basis',
                            $comparison?->evaluation_basis
                            ?? 'Lowest Evaluated Bid'
                        ) === $basis
                    )
                >
                    {{ $basis }}
                </option>

            @endforeach

        </select>

        @error('evaluation_basis')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror

    </div>


    {{-- Status --}}
    <div class="col-md-6">

        <label class="form-label">
            Status
            <span class="text-danger">*</span>
        </label>

        <select
            name="status"
            class="form-select @error('status') is-invalid @enderror"
            required
        >

            @foreach([
                'Draft',
                'Under Review',
                'Completed',
                'Approved',
                'Rejected',
            ] as $status)

                <option
                    value="{{ $status }}"
                    @selected(
                        old(
                            'status',
                            $comparison?->status ?? 'Draft'
                        ) === $status
                    )
                >
                    {{ $status }}
                </option>

            @endforeach

        </select>

        @error('status')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror

    </div>


    {{-- Summary --}}
    <div class="col-12">

        <label class="form-label">
            Summary
        </label>

        <textarea
            name="summary"
            rows="4"
            class="form-control @error('summary') is-invalid @enderror"
            placeholder="Enter comparison summary"
        >{{ old(
            'summary',
            $comparison?->summary
        ) }}</textarea>

        @error('summary')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror

    </div>


    {{-- Remarks --}}
    <div class="col-12">

        <label class="form-label">
            Remarks
        </label>

        <textarea
            name="remarks"
            rows="3"
            class="form-control @error('remarks') is-invalid @enderror"
            placeholder="Enter additional remarks"
        >{{ old(
            'remarks',
            $comparison?->remarks
        ) }}</textarea>

        @error('remarks')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror

    </div>

</div>