<form
    method="POST"
    action="{{ $action }}"
>

    @csrf

    @if(!empty($method))
        @method($method)
    @endif


    {{-- =========================================================
        INCIDENT IDENTIFICATION
    ========================================================== --}}

    <div class="card mb-4">

        <div class="card-header">
            <strong>Incident Information</strong>
        </div>

        <div class="card-body">

            <div class="row">

                {{-- Incident Number --}}

                <div class="col-md-4 mb-3">

                    <label class="form-label">
                        Incident Number
                    </label>

                    <input
                        type="text"
                        class="form-control"
                        value="{{ old(
                            'incident_number',
                            $incident->incident_number
                                ?? $incidentNumber
                                ?? 'Auto Generated'
                        ) }}"
                        readonly
                    >

                    <small class="text-muted">
                        Automatically generated by the system.
                    </small>

                </div>


                {{-- Incident Date --}}

                <div class="col-md-4 mb-3">

                    <label class="form-label">
                        Incident Date <span class="text-danger">*</span>
                    </label>

                    <input
                        type="date"
                        name="incident_date"
                        class="form-control @error('incident_date') is-invalid @enderror"
                        value="{{ old(
                            'incident_date',
                            isset($incident->incident_date)
                                ? $incident->incident_date->format('Y-m-d')
                                : now()->format('Y-m-d')
                        ) }}"
                        required
                    >

                    @error('incident_date')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror

                </div>


                {{-- Incident Time --}}

                <div class="col-md-4 mb-3">

                    <label class="form-label">
                        Incident Time
                    </label>

                    <input
                        type="time"
                        name="incident_time"
                        class="form-control @error('incident_time') is-invalid @enderror"
                        value="{{ old(
                            'incident_time',
                            $incident->incident_time ?? ''
                        ) }}"
                    >

                    @error('incident_time')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror

                </div>


                {{-- Location --}}

                <div class="col-md-6 mb-3">

                    <label class="form-label">
                        Incident Location <span class="text-danger">*</span>
                    </label>

                    <input
                        type="text"
                        name="location"
                        class="form-control @error('location') is-invalid @enderror"
                        value="{{ old(
                            'location',
                            $incident->location ?? ''
                        ) }}"
                        placeholder="Example: Block A - Level 3"
                        required
                    >

                    @error('location')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror

                </div>


                {{-- Incident Type --}}

                <div class="col-md-3 mb-3">

                    <label class="form-label">
                        Incident Type <span class="text-danger">*</span>
                    </label>

                    <select
                        name="incident_type"
                        class="form-select @error('incident_type') is-invalid @enderror"
                        required
                    >

                        <option value="">
                            Select Type
                        </option>

                        @foreach([
                            'Accident',
                            'Near Miss',
                            'First Aid',
                            'Medical Treatment',
                            'Lost Time Injury',
                            'Property Damage',
                            'Fire',
                            'Environmental',
                            'Vehicle',
                            'Equipment',
                            'Other'
                        ] as $type)

                            <option
                                value="{{ $type }}"
                                @selected(
                                    old(
                                        'incident_type',
                                        $incident->incident_type ?? ''
                                    ) === $type
                                )
                            >
                                {{ $type }}
                            </option>

                        @endforeach

                    </select>

                    @error('incident_type')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror

                </div>


                {{-- Severity --}}

                <div class="col-md-3 mb-3">

                    <label class="form-label">
                        Severity <span class="text-danger">*</span>
                    </label>

                    <select
                        name="severity"
                        class="form-select @error('severity') is-invalid @enderror"
                        required
                    >

                        <option value="">
                            Select Severity
                        </option>

                        @foreach([
                            'Low',
                            'Medium',
                            'High',
                            'Critical'
                        ] as $severity)

                            <option
                                value="{{ $severity }}"
                                @selected(
                                    old(
                                        'severity',
                                        $incident->severity ?? ''
                                    ) === $severity
                                )
                            >
                                {{ $severity }}
                            </option>

                        @endforeach

                    </select>

                    @error('severity')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror

                </div>


                {{-- Contractor --}}

                <div class="col-md-6 mb-3">

                    <label class="form-label">
                        Contractor
                    </label>

                    <select
                        name="contractor_id"
                        class="form-select @error('contractor_id') is-invalid @enderror"
                    >

                        <option value="">
                            Select Contractor
                        </option>

                        @foreach($contracts as $contract)

                            <option
                                value="{{ $contract->id }}"
                                @selected(
                                    (string) old(
                                        'contractor_id',
                                        $incident->contractor_id ?? ''
                                    ) === (string) $contract->id
                                )
                            >

                                {{ $contract->bidder_name ?? '—' }}

                                -

                                {{ $contract->contract_number }}

                            </option>

                        @endforeach

                    </select>

                    @error('contractor_id')

                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>

                    @enderror

                    <small class="text-muted">
                        Contractors are loaded from this project's contracts.
                    </small>

                </div>


                {{-- Reported By --}}

                <div class="col-md-6 mb-3">

                    <label class="form-label">
                        Reported By
                    </label>

                    <select
                        name="reported_by"
                        class="form-select @error('reported_by') is-invalid @enderror"
                    >

                        <option value="">
                            Current User
                        </option>

                        @foreach($users as $user)

                            <option
                                value="{{ $user->id }}"
                                @selected(
                                    (string) old(
                                        'reported_by',
                                        $incident->reported_by
                                            ?? auth()->id()
                                    ) === (string) $user->id
                                )
                            >
                                {{ $user->name }}
                            </option>

                        @endforeach

                    </select>

                    @error('reported_by')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                    @enderror

                </div>

            </div>

        </div>

    </div>


    {{-- =========================================================
        INCIDENT DESCRIPTION
    ========================================================== --}}

    <div class="card mb-4">

        <div class="card-header">
            <strong>Incident Description</strong>
        </div>

        <div class="card-body">

            <label class="form-label">
                What Happened? <span class="text-danger">*</span>
            </label>

            <textarea
                name="description"
                rows="7"
                class="form-control @error('description') is-invalid @enderror"
                placeholder="Describe the incident clearly, including what happened, where it happened and the circumstances..."
                required
            >{{ old(
                'description',
                $incident->description ?? ''
            ) }}</textarea>

            @error('description')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror

        </div>

    </div>


    {{-- =========================================================
        IMMEDIATE ACTION
    ========================================================== --}}

    <div class="card mb-4">

        <div class="card-header">
            <strong>Immediate Action Taken</strong>
        </div>

        <div class="card-body">

            <textarea
                name="immediate_action"
                rows="5"
                class="form-control @error('immediate_action') is-invalid @enderror"
                placeholder="Describe immediate actions taken after the incident..."
            >{{ old(
                'immediate_action',
                $incident->immediate_action ?? ''
            ) }}</textarea>

            @error('immediate_action')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror

        </div>

    </div>


    {{-- =========================================================
        INJURY
    ========================================================== --}}

    <div class="card mb-4">

        <div class="card-header">
            <strong>Injury Information</strong>
        </div>

        <div class="card-body">

            <div class="row">

                <div class="col-md-4 mb-3">

                    <label class="form-label d-block">
                        Did an injury occur?
                    </label>

                    <div class="form-check form-check-inline">

                        <input
                            class="form-check-input"
                            type="radio"
                            name="injury_occurred"
                            id="injury_yes"
                            value="1"
                            @checked(
                                old(
                                    'injury_occurred',
                                    $incident->injury_occurred ?? false
                                )
                            )
                        >

                        <label
                            class="form-check-label"
                            for="injury_yes"
                        >
                            Yes
                        </label>

                    </div>


                    <div class="form-check form-check-inline">

                        <input
                            class="form-check-input"
                            type="radio"
                            name="injury_occurred"
                            id="injury_no"
                            value="0"
                            @checked(
                                !old(
                                    'injury_occurred',
                                    $incident->injury_occurred ?? false
                                )
                            )
                        >

                        <label
                            class="form-check-label"
                            for="injury_no"
                        >
                            No
                        </label>

                    </div>

                </div>


                <div class="col-md-8 mb-3">

                    <label class="form-label">
                        Injury Details
                    </label>

                    <textarea
                        name="injury_details"
                        rows="4"
                        class="form-control"
                        placeholder="Describe injury, affected person, treatment, etc."
                    >{{ old(
                        'injury_details',
                        $incident->injury_details ?? ''
                    ) }}</textarea>

                </div>

            </div>

        </div>

    </div>


    {{-- =========================================================
        PROPERTY DAMAGE
    ========================================================== --}}

    <div class="card mb-4">

        <div class="card-header">
            <strong>Property / Equipment Damage</strong>
        </div>

        <div class="card-body">

            <div class="row">

                <div class="col-md-4 mb-3">

                    <label class="form-label d-block">
                        Property / Equipment Damage?
                    </label>

                    <div class="form-check form-check-inline">

                        <input
                            class="form-check-input"
                            type="radio"
                            name="property_damage"
                            id="damage_yes"
                            value="1"
                            @checked(
                                old(
                                    'property_damage',
                                    $incident->property_damage ?? false
                                )
                            )
                        >

                        <label
                            class="form-check-label"
                            for="damage_yes"
                        >
                            Yes
                        </label>

                    </div>


                    <div class="form-check form-check-inline">

                        <input
                            class="form-check-input"
                            type="radio"
                            name="property_damage"
                            id="damage_no"
                            value="0"
                            @checked(
                                !old(
                                    'property_damage',
                                    $incident->property_damage ?? false
                                )
                            )
                        >

                        <label
                            class="form-check-label"
                            for="damage_no"
                        >
                            No
                        </label>

                    </div>

                </div>


                <div class="col-md-8 mb-3">

                    <label class="form-label">
                        Damage Details
                    </label>

                    <textarea
                        name="property_damage_details"
                        rows="4"
                        class="form-control"
                        placeholder="Describe damaged property, equipment, estimated impact, etc."
                    >{{ old(
                        'property_damage_details',
                        $incident->property_damage_details ?? ''
                    ) }}</textarea>

                </div>

            </div>

        </div>

    </div>


    {{-- =========================================================
        WORK STOPPAGE
    ========================================================== --}}

    <div class="card mb-4">

        <div class="card-header">
            <strong>Work Stoppage</strong>
        </div>

        <div class="card-body">

            <div class="row">

                <div class="col-md-4 mb-3">

                    <label class="form-label d-block">
                        Was work stopped?
                    </label>

                    <div class="form-check form-check-inline">

                        <input
                            class="form-check-input"
                            type="radio"
                            name="work_stopped"
                            id="work_stopped_yes"
                            value="1"
                            @checked(
                                old(
                                    'work_stopped',
                                    $incident->work_stopped ?? false
                                )
                            )
                        >

                        <label
                            class="form-check-label"
                            for="work_stopped_yes"
                        >
                            Yes
                        </label>

                    </div>


                    <div class="form-check form-check-inline">

                        <input
                            class="form-check-input"
                            type="radio"
                            name="work_stopped"
                            id="work_stopped_no"
                            value="0"
                            @checked(
                                !old(
                                    'work_stopped',
                                    $incident->work_stopped ?? false
                                )
                            )
                        >

                        <label
                            class="form-check-label"
                            for="work_stopped_no"
                        >
                            No
                        </label>

                    </div>

                </div>


                <div class="col-md-8 mb-3">

                    <label class="form-label">
                        Work Stoppage Details
                    </label>

                    <textarea
                        name="work_stoppage_details"
                        rows="4"
                        class="form-control"
                        placeholder="Describe reason and duration of work stoppage..."
                    >{{ old(
                        'work_stoppage_details',
                        $incident->work_stoppage_details ?? ''
                    ) }}</textarea>

                </div>

            </div>

        </div>

    </div>


    {{-- =========================================================
        REMARKS
    ========================================================== --}}

    <div class="card mb-4">

        <div class="card-header">
            <strong>Remarks</strong>
        </div>

        <div class="card-body">

            <textarea
                name="remarks"
                rows="4"
                class="form-control"
                placeholder="Additional remarks..."
            >{{ old(
                'remarks',
                $incident->remarks ?? ''
            ) }}</textarea>

        </div>

    </div>


    {{-- =========================================================
        BUTTONS
    ========================================================== --}}

    <div class="d-flex justify-content-end">

        <a
            href="{{ route(
                'admin.projects.construction.hse.incidents.index',
                $project
            ) }}"
            class="btn btn-secondary me-2"
        >
            Cancel
        </a>


        <button
            type="submit"
            class="btn btn-primary"
        >

            @if(!empty($method))

                <i class="bi bi-check-circle me-1"></i>
                Update Incident

            @else

                <i class="bi bi-save me-1"></i>
                Report Incident

            @endif

        </button>

    </div>

</form>